# TODO: Update to use cmake build
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest

    packages:
    - g++-5
    - libboost1.55-dev
    - libeigen3-dev
    - libpng++-dev

before_script:
- (cd prj && ln -s def.compiler.gcc-5-ubuntu-14 def.compiler)
- (cd prj && ln -s def.platform.linux def.platform)

script:
- (cd prj     && export debug=false && make tests -j6    )
- (cd testing && export debug=false && ./run-all-tests.sh)
- (cd prj     && export debug=true  && make tests -j6    )
- (cd testing && export debug=true  && ./run-all-tests.sh)
